# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-15 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='tanggal_lahir',
        ),
    ]
