# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-15 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_postmodel_tanggal_lahir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='agree',
        ),
    ]
